### ISSUE TITLE
Crash on save image running QGIS 64bit 2.14, 2.16 on Windows 10

### ISSUE THREAD

**Issue by niko86** [mauroalberti/qProf#1]
The title describes my issue, I can provide the dump file generated if needed.

**Comment by mauroalberti** [comment]
The problem is, I suppose, related to saving an image from the main profile plot, where there is available the standard Matplotlib "save" button that exposes a flawed export format (jpeg, if I remember correctly). A present workaround is to export figures from the plugin "Export" tab, where only working formats are available. In the next release I have to remove the "save" button, or customize it by removing the crashing-causing formats.

**Comment by mauroalberti** [comment]
Checked "save" as jpeg in Linux QGIS 2.8 Wien, no QGIS crash. Possibly problem present only in Windows.

**Comment by niko86** [comment]
Yes must be just isolated to Windows. The export tab works well for csv so that's good enough for my needs. Thanks for making such a great plugin, I'll close the issue.
