### ISSUE TITLE
Error using qProf in QGIs 2.18: Couldn't load plugin 'qProf'

### ISSUE THREAD

**Issue by lluisvicens** [mauroalberti/qProf#7]
Hi Mauro,

Just to put a context around the error let me introduce myself. I'm Lluís from the GIS and Remote Sensing Service of the University of Girona and I'm a professor of the UNIGIS Msc. In the Geographic Analysis module my students are working on an assignment and they have to generate a topographic profile of the terrain.

I did recommend them the use of qProf but unfortunately some of them have experienced some problems and errors. One of my students tries to generate a profile from a route but it takes a lot of time and he coudn't get any result. QGIS freezes. Two days ago he get and error during the process and the plugin crashed. Now, when he tries to re-install the plugin he get the following error and he can't no longer install it. There is the error message attached.

Do you know where is the problem? Any hint?
Thanks in advance!
Cheers,
Lluís
[error_qprof.txt](https://github.com/mauroalberti/qProf/files/1698552/error_qprof.txt)

**Comment by mauroalberti** [comment]
For the route case, if it is composed by a quite large number of points, it could explain the long time required. Particularly if the DEM is not so small. I could test the plugin with this datasets, if you can share it.

The message error is probably related to trying to install qProf when using QGIS 2.18.**16** Windows (standalone installer) and to my knowledge this problem is impacting also other plugins. For what I understand, this particular packaging of QGIS for Windows has some flaws in the Python configuration so that the Python interpreter doesn't find the Tkinter module (that is in Python standard library, so it should be there). I had no problems with QGIS 2.18.15 (or older) - Win stand. inst.
Not sure if he can just dowload from _https://plugins.qgis.org/plugins/qProf_, unzip and put the folder (should be named _qProf_) in the Python plugin folder (e.g., in my case is _C:\Users\Mauro\.qgis2\python\plugins_) and it could work also in QGIS 2.18.16 Win.
Another possible workaround (suggested in Italian, sorry, by a known developer, I have not tried it) is:
"_..prova a cambiare il backend di matplotlib editando il file matplotlibrc localizzato in [cartella di installazione librerie di python]/matplotlib/mpl-data/matplotlibrc e cambiando il parametro "backend" da  backend: TkAgg a  backend: Qt4Agg come descritto in  http://matplotlib.org/faq/usage_faq.html#what-is-a-backend_ "

ciao,
mauro

**Comment by lluisvicens** [comment]
Hi Mauro,

I suggested your instructions to my student. I will let you know the results as soon as I know it. Thanks for your help.

Ciao,
Lluís

**Comment by naeemullah03** [comment]
Hello every body,
I want to make geological cross sections in QGIS 2.18, could any body help me that how i can do ? thanks
